### ISSUE TITLE
Call.method<type>(method,args) doesn't check the arguments

### ISSUE THREAD

**Issue by ShamanBlackout** [phantasma-io/TOMB#24]
Issue: It is possible to add in arguments to a method that does not require arguments and it is possible to leave arguments out of a method that requires arguments

```
contract test {

	global victory:bool;

	public win(from:address)
	{
		victory = true;
	}

	//Will compile although win takes 1 argument
    public callCheckResult(){
        if(victory){
            Call.method<method>(win);
        }
    }

	//Compiles with multiple arguments. 
	public callCheckResult2(){
		local badarg1: string ="bad";
		local badarg2: number = 3;
		local etc: bool = true;
        if(victory){
            Call.method<method>(win,badarg1,badarg2,etc);
        }
    }

	//compiles with 1 arg of type string while type needed is address
	public callCheckResult3(){
		local badarg1: string ="bad";
        if(victory){
            Call.method<method>(win,badarg1);
        }
    }

    constructor(owner:address){
        victory = false;

    }}
```

Call.method<type>(method,args):
 - Able to add in arguments to a method that takes none
 - Able to call a method takes argument without supplying any arguments.
 - Able to supply incorrect method type

**Comment by Relfos** [comment]
I've checked this today. Like I wrote in the other issue, Call.method is not supposed to be the main way to call private methods.

All Call.xxx are available for bypassing compiler limitations (same as the asm {} blocks), so those by design don't offer compile type check of arguments.

If you want proper argument checking please use the this.myMethod(myArg1, myArg2) syntax.
